name: Release

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        shell: powershell
        run: installer\build.ps1 -Version ${{ github.ref_name }}
      - name: Test
        shell: powershell
        run: ls -l .\build\
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .\build\WiXCover-${{ github.ref_name }}.msi
